name: Docker action
inputs:
  cmd:
    description: Command to be run on the container
    required: true
runs:
  using: "docker"
  image: "docker://ubuntu:latest"
  args: ["bash", "-c", "${{ inputs.cmd }}"]
