name: Docker action
inputs:
  commands:
    description: Command to be run on the container
    required: true
runs:
  using: "docker"
  image: "docker://ubuntu:latest"
  entrypoint: /bin/bash
  args: ["bash", "--help"]
  # args: ["${{ inputs.commands }}"]
  # using: "node12"
  # main: "index.js"
