name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - run: cat /home/runner/work/actions-playground/actions-playground/./.github/actions/docker-action/actions.yml
      - name: My first step
        uses: ./.github/actions/docker-action
        with:
          commands: "whoami"
