name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: docker --version
      - name: Look at volumes
        uses: docker://ubuntu:latest
        with:
          args: df
      - name: Look at /
        uses: ./.github/actions/docker-action
        with:
          cmd: |
            ls -la
            echo 'Hey'
      - name: Look at /github/home
        uses: ./.github/actions/docker-action
        with:
          cmd: cd /github/home && ls -la
      - name: JS Based action
        uses: ./.github/actions/docker-action-v2
        with:
          image: ubuntu:latest
          command: df
