name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: docker --version
      - run: ls -la
      - name: Look at volumes
        uses: docker://ubuntu:latest
        with:
          args: df
      - name: Look at /
        uses: ./.github/actions/docker-action
        with:
          cmd: |
            ls -la
            echo 'Hey'
      - name: Look at /github/home
        uses: ./.github/actions/docker-action
        with:
          cmd: cd /github/home && ls -la
      - name: Add MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: pass
          mysql user: developer
          mysql password: pass
      - name: JS Based action
        uses: ./.github/actions/docker-action-v2
        with:
          image: ubuntu:latest
          command: ls -la && apt-get update && apt-get install net-tools && netstat -tulpn
