name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: docker --version
      - name: Look at volumes
        uses: docker://ubuntu:latest
        with:
          args: df
      - name: Look at /
        uses: ./.github/actions/docker-action
        with:
          docker: ubuntu:latest
          cmd: |
            ls -la
            echo 'Hey'
      - name: Look at /github/home
        uses: ./.github/actions/docker-action
        with:
          docker: ubuntu:latest
          cmd: cd /github/home && ls -la
