name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - run: cat /home/runner/work/actions-playground/actions-playground/./.github/actions/docker-action/action.yml
      - run: docker --version
      - name: Look at volumes using action
        uses: ./.github/actions/docker-action
        with:
          cmd: df
      - name: Look at /
        uses: docker://ubuntu:latest
        with:
          args: ls -la
